services:
  - type: web
    name: deltav-db-explorer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120 --workers 1 --threads 4
    plan: free
